### ISSUE TITLE
amplify mockのような手元でdynamodbを動かして動作確認できるような形を調査する

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/JibungotoPlanet-backend#78]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
やりようはありそうなので、試してみる

**Comment by naoji3x** [comment]
@ayuki-joto 
ややオーバースペック気味ですが、localstackを使うとdynamodbやlambda, API gateway等のmockがローカルに構築できそうです。cdkのローカルでのテストにも使えるかもしれません。
https://github.com/localstack/localstack
