### ISSUE TITLE
CI/CD環境導入

### ISSUE THREAD

**Issue by t-kurasawa** [codeforjapan/JibungotoPlanet-backend#8]
フロントエンドと同様に husky と GitHub Actions で CI/CD 環境を準備したい
https://github.com/codeforjapan/JibungotoPlanet/issues/26

▼調査中
・バックエンドは Amplify で構築しており、Next は利用していないかどうか確認
・amplify/backend/function/ 配下で個別にソースコードがあるので読み込む
・Amplify での静的コード解析・テストの実行方法
・Amplify での CI/CD コマンド関連の有無

▼方針案
husky から Amplify の CI/CD コマンドを呼び出す

**Comment by naoji3x** [comment]
マージしました。ありがとうございます。.husky/pre-commit, pre-pushに実行権限を与える必要がありましたが無事動きました。
